const constants = {
    JOIN_CHAT: 'JOIN_CHAT',
    SEND_USER_CONFIRMATION: 'SEND_USER_CONFIRMATION',
    LEAVE_CHAT: 'LEAVE_CHAT',
    SEND_MESSAGE: 'SEND_MESSAGE',

    SET_USER: 'SET_USER',
    SET_INITIAL_USER: 'SET_INITIAL_USER'
}

export default constants
